name: Build SmartStarter Jar

on:
  workflow_dispatch:
  push: { branches: ["main"] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - uses: gradle/actions/setup-gradle@v4

      # settings.gradle: Loom repo 허용 (프로젝트 우선) + 필수 저장소
      - name: Write settings.gradle
        shell: bash
        run: |
          cat > settings.gradle << 'EOF'
          pluginManagement {
            repositories {
              maven { url 'https://maven.fabricmc.net/' }
              gradlePluginPortal()
            }
          }
          dependencyResolutionManagement {
            // Loom이 내부 repo를 추가하므로 프로젝트 우선으로 완화
            repositoriesMode.set(RepositoriesMode.PREFER_PROJECT)
            repositories {
              mavenCentral()
              maven { url 'https://maven.fabricmc.net/' }
              maven { name 'Mojang'; url 'https://libraries.minecraft.net/' }
            }
          }
          rootProject.name = 'SmartStarter-1.21.6'
          EOF

      # build.gradle: Yarn v2 맵핑 사용 (분리 JAR 대응), Fabric API는 제거
      - name: Write build.gradle
        shell: bash
        run: |
          cat > build.gradle << 'EOF'
          plugins {
              id 'fabric-loom' version '1.10.5'
              id 'maven-publish'
          }

          group = 'net.smartmoving'
          version = '1.0.0'

          dependencies {
              minecraft "com.mojang:minecraft:1.21.6"
              // ★ Yarn v2 맵핑 (분리 JAR 대응)
              mappings "net.fabricmc:yarn:1.21.6+build.1:v2"
              modImplementation "net.fabricmc:fabric-loader:0.16.14"
              // Fabric API는 필요해질 때만 추가
          }

          java {
              toolchain { languageVersion = JavaLanguageVersion.of(21) }
              withSourcesJar()
          }

          loom { splitEnvironmentSourceSets() }

          processResources {
              inputs.property "version", project.version
              filesMatching("fabric.mod.json") {
                  expand "version": project.version
              }
          }

          tasks.withType(JavaCompile).configureEach {
              options.encoding = "UTF-8"
              options.release = 21
          }

          jar {
              from("LICENSE") { rename { "LICENSE_\${project.name}" } }
          }
          EOF

      # (중요) 이전 실패로 남은 Loom/Gradle 캐시 정리
      - name: Clean Gradle/Loom caches
        shell: bash
        run: |
          rm -rf ~/.gradle/caches/* || true
          rm -rf ./.gradle || true

      # Gradle Wrapper 8.14.3 고정
      - name: Generate Gradle Wrapper (8.14.3)
        run: gradle wrapper --gradle-version 8.14.3

      # 빌드 + remapJar(배포용) 생성
      - name: Build (remap)
        run: |
          ./gradlew --stacktrace --warning-mode all --refresh-dependencies clean build remapJar
          echo "== Built files ==" && ls -al build/libs || true

      - name: Upload Jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: SmartStarter-jar
          # remapped 이름이 바뀌어도 잡히도록 폭넓게 지정
          path: |
            build/libs/*-remapped.jar
            build/libs/*-mapped.jar
            build/libs/*[0-9].jar
            build/libs/*.jar
          if-no-files-found: warn
